### PR TITLE
update favicons

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubernetes-sigs/lwkd/issues/157

### CODE REVIEW

**Comment by Arhell** [comment]
cc @jberkus

**Comment by Arhell** [comment]
> @Arhell thanks!
> 
> Any suggestions on ways to test this?

I tested locally.

**Comment by jberkus** [comment]
Some of the  mstile files are mostly empty space.  I'm not familiar with mstile; is there a reason for that?

**Comment by jberkus** [comment]
Asking Comms for help.

**Comment by Arhell** [comment]
> Asking Comms for help.

As I understand it, this was done specifically to place content, and since we only have an icon, it remains unchanged
https://docs.microsoft.com/ru-ru/previous-versions/windows/internet-explorer/ie-developer/samples/dn455106(v=vs.85)#static-tiles

**Comment by jberkus** [comment]
Wait, are mtiles for *Internet Explorer*?

If so, maybe just don't include those?  IE is going away.

**Comment by Arhell** [comment]
> Wait, are mtiles for _Internet Explorer_?
> 
> If so, maybe just don't include those? IE is going away.

I agree, but there are people who use this browser. They are few but they are. Just like a plus there will be no alert
https://realfavicongenerator.net/favicon_checker?protocol=https&site=lwkd.info%2F#.Ytc8BXbP23B

**Comment by sftim** [comment]
A tip, [SVG favicons](https://css-tricks.com/svg-favicons-in-action/) are a thing. Good with a raster image fallback.

**Comment by Arhell** [comment]
> A tip, [SVG favicons](https://css-tricks.com/svg-favicons-in-action/) are a thing. Good with a raster image fallback.

Done

**Review by jberkus — APPROVED** [review]

**Pull request merged**
